[package]
name = "axum-rs"
version = "0.1.0"
edition = "2021"
authors = ["axum.rs <team@axum.rs>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/axumrs/axum-rs"
homepage = "https://axum.rs"
description = "axum.rs网站系统"

[dependencies]
tokio = { version = "1", features = ["full"]}
axum = {version="0.6",features = ["headers"]}
serde = { version="1", features = ["derive"] }
chrono = { version="0.4", features=["serde"]}
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "mysql", "chrono" ] }
pulldown-cmark = "0.9"
redis = { version = "0.23", features = ["tokio-comp", "aio"] }
bcrypt = "0.14"
config = "0.13"
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
validator = { version = "0.16", features = ["derive"] }
tower-http = { version = "0.4", features = ["cors"] }
jsonwebtoken="8"
headers="0.3"
uaparser="0.6"
uuid =  {  version = "1", features = ["v4", "serde"]}
xid="1"
sha2="0.10"
base16ct="0.2"